language: java
jdk:
  - openjdk7

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p goroot && cd goroot
  - wget https://storage.googleapis.com/golang/go1.5.1.linux-amd64.tar.gz
  - tar -zxf go1.5.1.linux-amd64.tar.gz
  - rm -rf $GOROOT
  - export GOROOT=$TRAVIS_BUILD_DIR/goroot/go
  - export PATH=$PATH:$GOROOT/bin
  - go env
  - go version
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p $TRAVIS_BUILD_DIR/go/src $TRAVIS_BUILD_DIR/go/pkg $TRAVIS_BUILD_DIR/go/bin
  - export GOPATH=$TRAVIS_BUILD_DIR/go
  - export PATH=$PATH:$GOPATH/bin
  - cd $TRAVIS_BUILD_DIR/go/src && mkdir -p github.com/pingcap
  - cd github.com/pingcap && git clone https://github.com/pingcap/tidb.git
  - cd tidb && make parser && make server
  - git rev-parse HEAD
  - cd tidb-server
  - ./tidb-server -L fatal &
  - cd $TRAVIS_BUILD_DIR

script:
  - mvn clean test

notifications:
  email:
    recipients:
      - test@pingcap.com
    on_success: change
    on_failure: always